# LOAD in Numpy (Remember to pip install numpy first)

In [1]:
import numpy as np

# About Numpy: 
### Numpy is a python library work on multidimensional array and numpy array is faster as compare to  python lists  and used for scientific computing in python, numpy used in Statistics and Linear Algebra 

## How to write an array 

In [3]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


# Check the type of array

In [14]:
a = np.array([1])
print(a.dtype)    # as it is of integer type
a = np.array([1.5])
print(a.dtype) # as it is of float type
a = np.array(["a", "b", "c", "d"]) 
print(a.dtype) # as it is unicode string 
a = np.array([1.45644443333335555, 5.678444444444444444, 9.78966666666666666666666666666666]) 
print(a.dtype)

int32
float64
<U1
float64


# Check the dimension of array

In [8]:
a = np.array([[1, 2, 3, 4]  , [1, 4, 6, 7]])
print(a.ndim) # as it is 2 dimensional array
a = np.array([1])
print(a.ndim) # as it is 1 dimensional array
a = np.array([[[1, 2, 3, 4]  , [1, 4, 6, 7]],[[1, 2, 6, 7], [3, 4, 9, 8]]]) 
print(a.ndim) # as it is 3 dimensional array 

2
1
3


# How to check shape of an array

In [15]:
a = np.array([[1, 2, 3, 4]  , [1, 4, 6, 7]])
print(a.shape) # as it contains 2 rows and 4 coloumns

(2, 4)


# To check item size

In [18]:
a = np.array([[1, 2, 3, 4]  , [1, 4, 6, 7]])
print(a.itemsize) #  if you have a NumPy array of integers with a data type of int32, each element in the array takes up 4 bytes of memory, so the itemsize attribute would be 4.
print(a.nbytes) # Get total size
print(a.size) # total number of elements

4
32
8


# To get Specific Element of an array


In [32]:
a = np.array([[1, 2, 3, 4]  , [1, 4, 6, 7]])
a[1, 3]
a[0, :] # to get specific row of index 0
a[1, :] # to get specific row of index 1
a[:,3]  # to get specific column
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a[:,3 :-1:2] # to specific coloumn  starting with 3rd coulomn to last coloumn getting element with step size two 
a[0,: -1:2] # specific row starting with index zero and get the element of that row with step size  of 2

array([1, 3, 5])

#### In one dimensional it will show error --> if array is of [1, 2, 3, 4] thats it 
##### If you use the indexing expression a[:, 2] on the NumPy array a defined as np.array([[1, 2, 3, 4], [5, 6, 7, 8]]), it will return the values from all rows in the 3rd column (column with index 2) of the array a.

##### More specifically, the expression a[:, 2] means selecting all rows (denoted by :) and the 3rd column (denoted by 2, counting from zero-indexed column). Therefore, the resulting output would be a one-dimensional array [3, 7].

In [37]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)
a[1,5] = 20

a[:,2] = [1,2] # In Each row second coloumn get changes
print(a)
a[0,:] = [31, 49, 54, 67, 7, 9, 45] # In Each coloumn 1st element get interchanged
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[31 49 54 67  7  9 45]
 [ 8  9  2 11 12 20 14]]


# To get the specific element from 3d array

In [8]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# to get the specific element from the array

In [9]:
b[1,0,1]

6

# Intialising Different Type of Array

### For Zero matrix

In [12]:

c = np.zeros((2, 3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]


### All element is one in Matrix

In [15]:
d = np.ones((3, 2, 2))
print(d)
e = np.ones((3, 2, 2), dtype = "int32")
print(e)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]


### Any other matrix with all element same 

In [14]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

# How to get Identity matrix

In [19]:
np.identity((5), dtype = "int32")
# gives identity matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# numpy as random

In [16]:
np.random.rand(4,2)
# it gives number between 0 to 1 

array([[0.38985082, 0.4421048 ],
       [0.15057489, 0.39302579],
       [0.06598309, 0.07181637],
       [0.91553762, 0.62463505]])

In [17]:
np.random.randint(-4,8, size=(3,3))
# it gives the integers between - 4 to 8

array([[ 6, -2,  3],
       [ 2, -4, -2],
       [ 2, -1, -4]])

## How to repeat an array

In [26]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0)
print(r1)
r2 = np.repeat(arr,3, axis=1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


## How to change element in identity and zero matrix

In [27]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Copying an Array

In [28]:
import numpy as np
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics 

In [29]:
a = np.array([1,2,3,4])
print(a)
a + 2

[1 2 3 4]


array([3, 4, 5, 6])

In [30]:
a - 2

array([-1,  0,  1,  2])

In [31]:
a * 2

array([2, 4, 6, 8])

In [32]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [33]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [34]:
a ** 2

array([ 1,  4,  9, 16])

In [35]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra 

In [45]:
a = np.ones((2,2))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b) # For Matrix Multiply
c = np.linalg.inv(a)  
print(c)

[[1. 1.]
 [1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

# For Finding the Determinant 

In [44]:
c = np.full((4, 4), 7)
np.linalg.det(c)
 

0.0

## For DOT PRODUCT

In [39]:
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
dot = np.dot(a,b)  
print(dot)  

[[3400 6200]
 [ 374  712]]


# For Vector Product

In [38]:
a = np.array([[100,200],[23,12]])  
b = np.array([[10,20],[12,21]])  
vdot = np.vdot(a,b)  
print(vdot)  

5528


# For Inner Product

In [40]:
a = np.array([1,2,3,4,5,6])  
b = np.array([23,23,12,2,1,2])  
inner = np.inner(a,b)  
print(inner)  

130


## For finding Inverse Of Matrix

In [46]:
c = [[1,2], [3, 4]]
np.linalg.inv(c)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

# For Solving Linear Equation

In [47]:
a = np.array([[1,2],[3,4]])  
b = np.array([[1,2],[3,4]])  
print(np.linalg.solve(a, b))  

[[1.00000000e+00 0.00000000e+00]
 [8.32667268e-17 1.00000000e+00]]
